# Generated by Django 5.1.3 on 2025-07-31 08:05

import apps.scans.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="temp/scans/")),
                ("bbox_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_processed", models.BooleanField(default=False)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_scans",
                        to="patients.patient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScanResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(blank=True, max_length=100)),
                (
                    "stl_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.scans.models.patient_scan_upload_to,
                    ),
                ),
                (
                    "depth_map_8bit",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.scans.models.patient_scan_upload_to,
                    ),
                ),
                (
                    "depth_map_16bit",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.scans.models.patient_scan_upload_to,
                    ),
                ),
                (
                    "preview_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.scans.models.patient_scan_upload_to,
                    ),
                ),
                ("volume_estimate", models.FloatField(blank=True, null=True)),
                ("processing_metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="scans.scan",
                    ),
                ),
            ],
        ),
    ]
