# Generated by Django 5.1.3 on 2025-07-31 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scans", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scan",
            name="bbox_data",
        ),
        migrations.RemoveField(
            model_name="scan",
            name="image",
        ),
    ]
