# Generated by Django 5.1.3 on 2025-07-31 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scans", "0002_restructure_scan_lightweight"),
    ]

    operations = [
        migrations.AddField(
            model_name="scan",
            name="session_id",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
