# Generated by Django 5.1.3 on 2025-07-31 09:21

from django.db import migrations
import uuid


def populate_session_ids(apps, schema_editor):
    """Populate session_id for existing Scan records"""
    Scan = apps.get_model("scans", "Scan")
    for scan in Scan.objects.filter(session_id__isnull=True):
        scan.session_id = uuid.uuid4()
        scan.save(update_fields=["session_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("scans", "0003_add_session_id_nullable"),
    ]

    operations = [
        migrations.RunPython(
            populate_session_ids, 
            reverse_code=migrations.RunPython.noop
        ),
    ]
