# Generated by Django 5.1.3 on 2025-07-31 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("scans", "0004_populate_session_id_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="session_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
