# Generated by Django 5.1.3 on 2025-08-01 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_processing", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AIModel",
        ),
    ]
